# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-0hhyUR0WbPVHRjVvgp2W3mjAs1hgV1
"""

import pandas
from math import inf

dataFrame=pandas.read_excel('DATASET.xlsx')
dataFrame=dataFrame.drop(columns=['Example'])

testData = ('T', 'T', 'F', 'T', 'Some', '$$$', 'T', 'T', 'Italian', '>60')
cls = 'Target Wait'

mx_prob=(-inf,None)
features=[feat for feat in dataFrame.columns if feat != cls]
x1 = dataFrame.groupby(cls)
for label,tdf in dataFrame.groupby(cls):
  tdf_prob=1 
  tdf_len=len(tdf) + 1
  length=len(data_list)
  for index, column in enumerate(features):
      tdf_prob *= (1+len(tdf.loc[tdf[column] == testData[index]]))/tdf_len
  tdf_prob *= tdf_len/length
  if tdf_prob>mx_prob[0]:
      mx_prob=(tdf_prob, label)
print("Label for given test data is ",mx_prob[1])